src/home/urls.py
from django.urls import path

from .views import Index

app_name = 'home'
urlpatterns = [
    path('', Index.as_view(), name='index')
]

src/mass_aquaponics/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
]

src/iot/models.py
from django.db.models import Model, CharField, IntegerField
from django.core.validators import MinLengthValidator

# Create your models here.

class CommunityBroker (Model):
    '''
    The CommunityBroker will store the information
    necessary to connect to an MQTT broker wich 
    intermediates communication between the server 
    and each system inside a community.
    '''

    #The public name of the community
    name            = CharField(max_length=20)
    #Address where the MQTT broker resides
    host            = CharField(max_length=30)
    port            = IntegerField()
    #Optional broker credentials to add cyber security for the community
    cred_username   = CharField(max_length=20, null=True)
    cred_password   = CharField(max_length=20, null=True)
    #if credentials aren't used, set 
    #cred_username=None; cred_password=None

    def __repr__ (self):
        return f'<COMMUNITY BROKER {self.pk} | {self.name} on {self.host}:{self.port}>'

src/home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

# Create your views here.

class Index (TemplateView):
    template_name = 'home/about.html'

src/home/templates/base.html
{% load render_bundle from webpack_loader %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% render_bundle 'imports'  'css' 'HOME' %}
    {% render_bundle 'basic'    'css' 'HOME' %}
    {% block head %}
    {% endblock %}
    <title>{% block title %}Generic{% endblock %} - Mass Aquaponics</title>
</head>
<body>
    {% include 'header.html' %}
    <main class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                {% block content %}
                    <div class="pt-4 pb-4">
                        <p class="text-muted text-center">page currently empty</p>
                    </div>
                {% endblock %}
            </div>
        </div>
    </main>
    {% include 'footer.html' %}
    {% render_bundle 'imports'  'js' 'HOME' %}
    {% render_bundle 'basic'    'js' 'HOME' %}
</body>
</html>

src/home/templates/footer.html
<footer class="page-footer font-small bg-light pt-3">
  <div class="container-fluid text-center">
    <div class="row">
      <div class="col-md-4 offset-md-2">
        <label class="text-uppercase">Developers</label>
        <ul class="list-unstyled">
          <li>Hafael Thor Macêdo Ferreira</li>
          <li>Jorbr Freire</li>
        </ul>
      </div>
      <div class="col-md-4">
        <label class="text-uppercase">Links</label>
        <ul class="list-unstyled">
          <li><a href="https://github.com/hafaelthor/MassAquaponics">GitHub</a></li>
        </ul>
      </div>
    </div>
    <div class="footer-copyright text-center pt-4">© 2019 MassAquaponics</div>
  </div>
</footer>

src/home/templates/header.html
<nav class="navbar navbar-expand-md navbar-light bg-light">
    <a href="{% url 'home:index' %}" class="navbar-brand">Mass Aquaponics</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" 
        data-target="#navbar-content-collapse" aria-controls="navbar-content-collapse" 
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar-content-collapse">
        <ul class="navbar-nav mr-auto">
            {% if True %}
                {# will be available when authenticated #}
                <li class="nav-item">
                    <a href="#" class="nav-link">Feed</a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">Dashboard</a>
                </li>
            {% else %}
                {# will be available when not authenticated #}
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="#">About Us</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            {% if True %}
                {# will be available when authenticated #}
                <li class="nav-item">
                    <a class="nav-link" href="#">Profile</a>
                <li class="nav-item">
                    <a class="nav-link text-danger" href="#">Log Out</a>
                </li>
            {% else %}
                {# will be available when not authenticated #}
                <li class="nav-item">
                    <a class="nav-link" href="#">Sign Up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-success" href="#">Log In</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

src/home/templates/home/about.html
{% extends 'base.html' %}

{% block title %}About Us{% endblock %}